version: 2.1

orbs:
    python: circleci/python@0.2.1

jobs:
    build-and-test:
        executor: python/default
        steps:
            - checkout
            - python/load-cache
            - python/install-deps
            - python/save-cache
            - run:
                    command: python -m tox
                    name: Test

workflows:
    master:
        jobs:
            - build-and-test:
                filters:
                    branches:
                        only: master

    dev:
        jobs:
            - build-and-test:
                filters:
                    branches:
                        only: dev

